### ISSUE TITLE
Avoid quotes in space seperated strings

### ISSUE THREAD

**Issue by amirsaleem96** [jamesr73/quote-words#1]
Quote word is adding quotes on each word in a string which is space separated. I want quotes to appear in every new line and not in space seprated strings. Here is the example,

Problem
--------------------------------------------------------------------

French Polynesia => "French" "Polynesia"
French Southern Territories => "French" "Southern" "Territories"

Required
--------------------------------------------------------------------

French Polynesia => "French Polynesia"
French Southern Territories => "French Southern Territories"

**Comment by jamesr73** [comment]
Simple 3 character change. Remembering how to publish it will be more tricky ;-)

**Comment by jamesr73** [comment]
I have incorporated this request because it aligns with the original use case for the package... to quote comma/punctuation separated words.

It took more than 3 characters ;-) Tests added and documentation updated with the examples above.

Version 0.2.0 is available for download from atom.io.

Thank you for your input.

**Comment by amirsaleem96** [comment]
Great, now my problem has been solved. Actually, I have lots of JSON data so your package is very helpful.
Thanks.

**Comment by jamesr73** [comment]
You're welcome. I originally created the package to help with generating JSON data, so I'm glad to hear you find it useful for that too. :-)
